---
- name: Installation des serveurs web
  hosts: web
  remote_user: root
  tasks:
    - name: Installation des tools
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - vim
        - htop
        - git
        - zsh
